document.write("<ul class='icons'>");
document.write("<li><a href='https://github.com/aibhleog' class='icon alt fa-github'><span class='label'>GitHub</span></a></li>");
document.write("<li><a href='https://twitter.com/aibhleog' class='icon alt fa-twitter'><span class='label'>Twitter</span></a></li>");
document.write("<li><a href='https://www.instagram.com/gingersnapmadcap/' class='icon alt fa-instagram'><span class='label'>Instagram</span></a></li>");
document.write("</ul>");
document.write("<ul class='copyright'>");
document.write("<li><strong><font color='#589FCE'>astro.hutchison AT gmail.com</font></strong></li>");
document.write("<li>&copy; Taylor Hutchison</li>");
document.wirte("<li>Design: <a href='https://html5up.net'>HTML5 UP</a></li>");
//document.write("</ul>");
