document.write("<ul class='links'>");
document.write("<li><a href='index.html'>Home</a></li>");
document.write("<li><a href='aboutme.html'>About Me</a></li>");
document.write("<li><a href='research.html'>Research</a></li>");
document.write("<li><a href='github.html'>Github Projects</a></li>");
document.write("<li><a href='cv.html'>CV &amp; Highlights</a></li>");
document.write("<li><a href='nsf.html'>NSF GRFP Advice</a></li>");
document.write("<li><a href='photo-gallery/index.html'>Photo Gallery</a></li>");
document.write("<li><a href='useful.html'>Resources</a></li>");
document.write("</ul>");
